[tasks]
build = "docker build -t ruby-server ."
run = "docker run -p 3000:3000 --memory=1g --memory-swap=1g ruby-server"
server = "docker build -t ruby-server . && docker run -p 3000:3000 --memory=1g --memory-swap=1g ruby-server"
benchmark = "ab -n 1000 -c 10 http://localhost:3000/"
